# Copyright (c) 2023, Crash Override, Inc.
#
# This file is part of Chalk
# (see https://crashoverride.com/docs/chalk)
from pathlib import Path
import zipfile

import pytest

from .chalk.runner import Chalk
from .conf import ZIPS
from .utils.log import get_logger


logger = get_logger()

# Test data fixtures
PYTHON_LAMBDA_ZIP = ZIPS / "python" / "my_deployment_package.zip"
NODEJS_LAMBDA_ZIP = ZIPS / "nodejs" / "function.zip"
GOLANG_LAMBDA_ZIP = ZIPS / "golang" / "myFunction.zip"
MISC_LAMBDA_ZIP = ZIPS / "misc" / "misc.zip"
EMPTY_ZIP = ZIPS / "empty" / "empty.zip"


@pytest.mark.slow()
@pytest.mark.parametrize(
    "copy_files",
    [
        [ZIPS / "nodejs" / "function.zip"],
        [ZIPS / "python" / "my_deployment_package.zip"],
    ],
    indirect=True,
)
@pytest.mark.parametrize("virtual", [True, False])
def test_valid_slow(
    tmp_data_dir: Path,
    chalk: Chalk,
    copy_files: list[Path],
    virtual: bool,
):
    test_file = copy_files[0]

    # chalk reports generated by insertion, json array that has one element
    insert = chalk.insert(artifact=tmp_data_dir, virtual=virtual)
    assert insert.report.marks_by_path.contains({str(test_file): {}})

    # array of json chalk objects as output, of which we are only expecting one
    extract = chalk.extract(artifact=tmp_data_dir, virtual=virtual)
    if not virtual:
        assert extract.report.marks_by_path.contains({str(test_file): {}})


@pytest.mark.parametrize(
    "copy_files",
    [
        # empty zip file does not get chalked, so no artifact info
        [ZIPS / "empty" / "empty.zip"],
    ],
    indirect=True,
)
@pytest.mark.parametrize("virtual", [True, False])
def test_empty(
    tmp_data_dir: Path,
    copy_files: list[Path],
    chalk: Chalk,
    virtual: bool,
):
    # no _CHALK will be generated on an unchalked empty zip
    assert chalk.insert(
        artifact=tmp_data_dir,
        virtual=virtual,
        expecting_chalkmarks=False,
    )
    assert chalk.extract(
        artifact=tmp_data_dir,
        virtual=virtual,
        expecting_chalkmarks=False,
    )


@pytest.mark.parametrize(
    "copy_files",
    [
        [ZIPS / "misc" / "misc.zip"],
        [ZIPS / "golang" / "myFunction.zip"],
    ],
    indirect=True,
)
@pytest.mark.parametrize("virtual", [True, False])
def test_valid(
    tmp_data_dir: Path,
    chalk: Chalk,
    copy_files: list[Path],
    virtual: bool,
):
    test_file = copy_files[0]

    # chalk reports generated by insertion, json array that has one element
    insert = chalk.insert(artifact=tmp_data_dir, virtual=virtual)
    # we are only checking the ZIP chalk mark, not any of the subchalks
    assert insert.report.marks_by_path.contains({str(test_file): {}})

    # array of json chalk objects as output, of which we are only expecting one
    extract = chalk.extract(artifact=tmp_data_dir, virtual=virtual)
    if not virtual:
        assert extract.report.marks_by_path.contains({str(test_file): {}})


def verify_chalk_binary_in_zip(zip_path: Path):
    """Helper function to verify chalk binary exists in the zip file."""
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        # Verify the chalk binary was added
        assert "chalk" in zip_ref.namelist()


@pytest.mark.parametrize(
    "copy_files",
    [
        [PYTHON_LAMBDA_ZIP],
        [NODEJS_LAMBDA_ZIP],
    ],
    indirect=True,
)
def test_lambda_insert(
    tmp_data_dir: Path,
    chalk: Chalk,
    copy_files: list[Path],
):
    """Test `chalk insert --inject-binary` adds the binary to the zip."""
    test_file = copy_files[0]

    # Run chalk insert with the --inject-binary
    insert = chalk.insert(artifact=tmp_data_dir, virtual=False, inject_binary=True)

    # Verify the chalk mark was added
    # assert str(test_file) in insert.marks_by_path.keys()
    # assert insert.marks_by_path[str(test_file)].contains({"_OP_ARTIFACT_TYPE": "ZIP"})
    # # Verify only one was added
    # assert len(insert.marks) == 1
    assert insert.mark.has(
        PATH_WHEN_CHALKED=str(test_file),
        _OP_ARTIFACT_TYPE="ZIP",
    )

    # Verify chalk binary was added to the zip
    verify_chalk_binary_in_zip(test_file)


@pytest.mark.parametrize(
    "copy_files",
    [
        [PYTHON_LAMBDA_ZIP],
    ],
    indirect=True,
)
def test_lambda_extract_after_insert(
    tmp_data_dir: Path,
    chalk: Chalk,
    copy_files: list[Path],
):
    """Test extraction works correctly after insertion.

    After inserting chalk binary with --inject-binary flag, we should be able to
    extract the chalk marks without errors, and the marks should
    identify the file as a ZIP artifact.
    """
    test_file = copy_files[0]

    # First insert a chalk mark with --inject-binary flag
    insert = chalk.insert(artifact=tmp_data_dir, virtual=False, inject_binary=True)
    assert insert.marks_by_path.contains({str(test_file): {}})
    assert insert.mark.contains({"_OP_ARTIFACT_TYPE": "ZIP"})

    # Now extract and verify we can read the chalk mark
    extract = chalk.extract(artifact=tmp_data_dir)
    assert extract.marks_by_path.contains({str(test_file): {}})
    assert extract.mark.contains({"_OP_ARTIFACT_TYPE": "ZIP"})
    # keys common between `insert` and `extract` are equal
    assert all(
        insert.mark[key] == extract.mark[key]
        for key in insert.mark.keys() & extract.mark.keys()
    )


@pytest.mark.parametrize(
    "copy_files",
    [
        [GOLANG_LAMBDA_ZIP],
        [MISC_LAMBDA_ZIP],
    ],
    indirect=True,
)
def test_lambda_with_other_lambda_zips(
    tmp_data_dir: Path,
    chalk: Chalk,
    copy_files: list[Path],
):
    """Test the --inject-binary flag with full suite of lambda zip fixutres.

    The binary insertion should work with various zip archives used for
    different lambda fixutures (Go, misc).
    """
    test_file = copy_files[0]

    # Run chalk insert with the --inject-binary flag
    insert = chalk.insert(artifact=tmp_data_dir, virtual=False, inject_binary=True)

    # Verify the chalk mark was added
    assert insert.marks_by_path.contains({str(test_file): {}})
    assert insert.mark.contains({"_OP_ARTIFACT_TYPE": "ZIP"})

    # Verify chalk binary was added to the zip
    extract_dir = tmp_data_dir / "extracted"
    verify_chalk_binary_in_zip(test_file)
