# Pre-commit hooks for serverless-plugin-crashoverride
# See https://pre-commit.com for more information

repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=128"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml

  # Local hooks for npm scripts
  - repo: local
    hooks:
      # ESLint
      - id: eslint
        name: ESLint
        entry: npm run lint
        language: system
        files: ^src/.*\.ts$
        pass_filenames: false
        stages: [commit]

      # Prettier formatting
      - id: prettier
        name: Prettier Format
        entry: npm run format
        language: system
        files: ^src/.*\.ts$
        pass_filenames: false
        stages: [commit]

      # TypeScript compilation check
      - id: typescript-build
        name: TypeScript Build Check
        entry: npm run build
        language: system
        files: ^src/.*\.ts$
        pass_filenames: false
        stages: [commit]

      # Run tests
      - id: jest-tests
        name: Jest Tests
        entry: npm test
        language: system
        files: ^src/.*\.(ts|test\.ts)$
        pass_filenames: false
        stages: [commit]
