name: lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    if: |
      !contains(github.event.pull_request.body, format('skip:{0}', github.workflow))

    concurrency:
      # only allow one job per PR running
      # older pending jobs will be cancelled not to waste CI minutes
      # cannot use github.job here https://github.com/community/community/discussions/13496
      group: ${{ github.workflow }}-pre-commit-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # 3.1.4

      - name: Run pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # 3.0.0
